- שם: הגדרת סביבת Node.js
  שימושים: actions/setup-node@v3.5.1
  עם:
    # הגדר אישור תמיד ב-npmrc.
    always-auth: # אופציונלי, ברירת המחדל היא שקר
    # מפרט גרסה של הגרסה שבה יש להשתמש. דוגמאות: 12.x, 10.15.1, >=10.15.0.
    גירסת צומת: # אופציונלי
    # קובץ המכיל את מפרט הגרסה של הגרסה שבה יש להשתמש. דוגמאות: .nvmrc, .node-version, .tool-versions.
    node-version-file: # אופציונלי
    # ארכיטקטורת יעד לשימוש של Node. דוגמאות: x86, x64. ישתמש בארכיטקטורת מערכת כברירת מחדל.
    ארכיטקטורה: # אופציונלי
    # הגדר אפשרות זו אם ברצונך שהפעולה תבדוק את הגרסה הזמינה העדכנית ביותר שעונה על מפרט הגרסה.
    בדיקה אחרונה: # אופציונלי
    # רישום אופציונלי להגדרה לאימות. יגדיר את הרישום בקובץ npmrc ו-.yarnrc ברמת הפרויקט, ויגדיר אישור לקריאה מ-env.NODE_AUTH_TOKEN.
    כתובת אתר הרישום: # אופציונלי
    # טווח אופציונלי לאימות מול רישום עם היקף. יחזור לבעל המאגר בעת שימוש ברישום חבילות GitHub (https://npm.pkg.github.com/).
    היקף: # אופציונלי
    # משמש למשיכת הפצות צמתים מגרסאות צומת. מכיוון שיש ברירת מחדל, זה בדרך כלל לא מסופק על ידי המשתמש.
    אסימון: # אופציונלי, ברירת המחדל היא ${{ github.token }}
    # משמש לציון מנהל חבילות לאחסון במטמון בספריית ברירת המחדל. ערכים נתמכים: npm, yarn, pnpm.
    מטמון: # אופציונלי
    # משמש כדי לציין את הנתיב לקובץ תלות: package-lock.json, yarn.lock, וכו'. תומך בתווים כלליים או ברשימת שמות קבצים לאחסון תלות מרובות.
    cache-dependency-path: # אופציונלי
